
server:
  port: 8080

spring:
  application:
    name: rpush-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://rpush-eureka:8761/eureka

zuul:
  routes:
    rpush-route:
      path: /route/**
      serviceId: rpush-route
    rpush-server:
      path: /server/**
      serviceId: rpush-server

management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics
  metrics:
    tags:
      application: ${rpush-route}
